// It is used by the Kolenu app to authorize downloads from Cloudflare R2 CDN.
String getCloudflareDownloadKey() => "Dummy base64-encoded 32-byte key, replace with actual key generated by security/generate_keys.sh";
